version: '3.8'

services:
  mysql:
    image: postgres:latest
    container_name: postgres
    restart: always
    env_file: .env
    ports:
      - '${POSTGRES_PORT}:5432'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
